// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "appengine": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/appengine01/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/appengine01
// --version=v1.3.0

package client

import (
	"net/http"
)

// example MediaType (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	Message *string `form:"message,omitempty" json:"message,omitempty" xml:"message,omitempty"`
}

// DecodeExample decodes the Example instance encoded in resp body.
func (c *Client) DecodeExample(resp *http.Response) (*Example, error) {
	var decoded Example
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
