// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "appengine": Application User Types
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/appengine01/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/appengine01
// --version=v1.3.0

package client
