basePath: /api
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Account:
    description: A account (default view)
    example:
      googleUserID: Et iure accusamus doloremque qui magnam assumenda.
      lastLogin: 2012-02-25T05:57:31Z
      name: In voluptas placeat est.
      picture: Occaecati explicabo eos ipsa dolorem accusantium.
    properties:
      googleUserID:
        example: Et iure accusamus doloremque qui magnam assumenda.
        type: string
      lastLogin:
        example: 2012-02-25T05:57:31Z
        format: date-time
        type: string
      name:
        example: In voluptas placeat est.
        type: string
      picture:
        example: Occaecati explicabo eos ipsa dolorem accusantium.
        type: string
    required:
    - googleUserID
    - picture
    - lastLogin
    title: 'Mediatype identifier: application/vnd.account+json; view=default'
    type: object
  AccountCollection:
    description: AccountCollection is the media type for an array of Account (default
      view)
    example:
    - googleUserID: Et iure accusamus doloremque qui magnam assumenda.
      lastLogin: 2012-02-25T05:57:31Z
      name: In voluptas placeat est.
      picture: Occaecati explicabo eos ipsa dolorem accusantium.
    - googleUserID: Et iure accusamus doloremque qui magnam assumenda.
      lastLogin: 2012-02-25T05:57:31Z
      name: In voluptas placeat est.
      picture: Occaecati explicabo eos ipsa dolorem accusantium.
    items:
      $ref: '#/definitions/Account'
    title: 'Mediatype identifier: application/vnd.account+json; type=collection; view=default'
    type: array
  Message:
    description: A Message (default view)
    example:
      auther: Aut laboriosam corporis ducimus beatae occaecati temporibus.
      content: r4jwj9vhp
      created: 2013-09-21T07:19:10Z
      id: 5.176059e+18
    properties:
      auther:
        example: Aut laboriosam corporis ducimus beatae occaecati temporibus.
        type: string
      content:
        example: r4jwj9vhp
        maxLength: 400
        minLength: 1
        type: string
      created:
        example: 2013-09-21T07:19:10Z
        format: date-time
        type: string
      id:
        example: 5.176059e+18
        format: int64
        type: integer
    required:
    - id
    - content
    - auther
    - created
    title: 'Mediatype identifier: application/vnd.message+json; view=default'
    type: object
  MessageCollection:
    description: MessageCollection is the media type for an array of Message (default
      view)
    example:
    - auther: Aut laboriosam corporis ducimus beatae occaecati temporibus.
      content: r4jwj9vhp
      created: 2013-09-21T07:19:10Z
      id: 5.176059e+18
    - auther: Aut laboriosam corporis ducimus beatae occaecati temporibus.
      content: r4jwj9vhp
      created: 2013-09-21T07:19:10Z
      id: 5.176059e+18
    items:
      $ref: '#/definitions/Message'
    title: 'Mediatype identifier: application/vnd.message+json; type=collection; view=default'
    type: array
  MessagePayload:
    example:
      auther: Quas quas doloribus repudiandae tempora ut nihil.
      content: oi6k48
      created: 2000-04-16T11:52:34Z
    properties:
      auther:
        example: Quas quas doloribus repudiandae tempora ut nihil.
        type: string
      content:
        example: oi6k48
        maxLength: 400
        minLength: 1
        type: string
      created:
        example: 2000-04-16T11:52:34Z
        format: date-time
        type: string
    required:
    - content
    - auther
    - created
    title: MessagePayload
    type: object
  Room:
    description: A room (default view)
    example:
      created: 1971-07-23T11:02:36Z
      description: room description
      name: room001
    properties:
      created:
        description: Date of creation
        example: 1971-07-23T11:02:36Z
        format: date-time
        type: string
      description:
        description: description of room
        example: room description
        maxLength: 400
        type: string
      name:
        description: Name of room
        example: room001
        maxLength: 20
        minLength: 3
        pattern: '[a-z|0-9]+'
        type: string
    required:
    - name
    - description
    - created
    title: 'Mediatype identifier: application/vnd.room+json; view=default'
    type: object
  RoomCollection:
    description: RoomCollection is the media type for an array of Room (default view)
    example:
    - created: 1971-07-23T11:02:36Z
      description: room description
      name: room001
    - created: 1971-07-23T11:02:36Z
      description: room description
      name: room001
    items:
      $ref: '#/definitions/Room'
    title: 'Mediatype identifier: application/vnd.room+json; type=collection; view=default'
    type: array
  RoomPayload:
    example:
      created: 2006-06-06T04:07:42Z
      description: room description
      name: room001
    properties:
      created:
        description: Date of creation
        example: 2006-06-06T04:07:42Z
        format: date-time
        type: string
      description:
        description: description of room
        example: room description
        maxLength: 400
        type: string
      name:
        description: Name of room
        example: room001
        maxLength: 20
        minLength: 3
        pattern: '[a-z|0-9]+'
        type: string
    required:
    - name
    - description
    title: RoomPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:9089
info:
  description: goa study chat api
  title: goa study chat
  version: ""
paths:
  /accounts:
    get:
      description: Retrieve account with given id or something
      operationId: account#show
      parameters:
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: ids
        required: false
        type: array
      produces:
      - application/vnd.goa.error
      - application/vnd.account+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AccountCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show account
      tags:
      - account
  /accounts/me:
    get:
      description: |-
        Retrieve my account

        Required security scopes:
          * `api:access`
      operationId: account#showMe
      produces:
      - application/vnd.goa.error
      - application/vnd.account+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: showMe account
      tags:
      - account
  /rooms:
    get:
      description: Retrieve all rooms.
      operationId: room#list
      parameters:
      - in: query
        name: limit
        required: false
        type: integer
      - in: query
        name: offset
        required: false
        type: integer
      produces:
      - application/vnd.room+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RoomCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list room
      tags:
      - room
    post:
      description: |-
        Create new Room

        Required security scopes:
          * `api:access`
      operationId: room#post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RoomPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: /rooms/[0-9]+
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: post room
      tags:
      - room
  /rooms/{name}:
    get:
      description: Retrieve room with given name
      operationId: room#show
      parameters:
      - description: Name of room
        in: path
        maxLength: 20
        minLength: 3
        name: name
        pattern: '[a-z|0-9]+'
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.room+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Room'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show room
      tags:
      - room
  /rooms/{name}/messages:
    get:
      description: Retrieve all messages.
      operationId: message#list
      parameters:
      - in: query
        name: limit
        required: false
        type: integer
      - description: Name of room
        in: path
        maxLength: 20
        minLength: 3
        name: name
        pattern: '[a-z|0-9]+'
        required: true
        type: string
      - in: query
        name: offset
        required: false
        type: integer
      produces:
      - application/vnd.message+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/MessageCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list message
      tags:
      - message
    post:
      description: |-
        Create new message

        Required security scopes:
          * `api:access`
      operationId: message#post
      parameters:
      - description: Name of room
        in: path
        maxLength: 20
        minLength: 3
        name: name
        pattern: '[a-z|0-9]+'
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/MessagePayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: ^/rooms/[0-9]+/messages/[0-9]+$
              type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: post message
      tags:
      - message
  /rooms/{name}/messages/{messageID}:
    get:
      description: Retrieve message with given id
      operationId: message#show
      parameters:
      - in: path
        name: messageID
        required: true
        type: integer
      - description: Name of room
        in: path
        maxLength: 20
        minLength: 3
        name: name
        pattern: '[a-z|0-9]+'
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.message+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show message
      tags:
      - message
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  BadRequest:
    description: Bad Request
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Account'
  Unauthorized:
    description: Unauthorized
schemes:
- http
securityDefinitions:
  jwt:
    description: |2-


      **Security Scopes**:
        * `api:access`: API access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
