// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "GAE Chat API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/gae-chat/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/gae-chat
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// AccountHref returns the resource href.
func AccountHref() string {
	return "/api/accounts"
}

// MessageHref returns the resource href.
func MessageHref(name, messageID interface{}) string {
	paramname := strings.TrimLeftFunc(fmt.Sprintf("%v", name), func(r rune) bool { return r == '/' })
	parammessageID := strings.TrimLeftFunc(fmt.Sprintf("%v", messageID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/rooms/%v/messages/%v", paramname, parammessageID)
}

// RoomHref returns the resource href.
func RoomHref(name interface{}) string {
	paramname := strings.TrimLeftFunc(fmt.Sprintf("%v", name), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/rooms/%v", paramname)
}
