// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "appengine": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/appengine01/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/appengine01
// --version=v1.3.0

package app

// example MediaType (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	Message *string `form:"message,omitempty" json:"message,omitempty" xml:"message,omitempty"`
}
