/**
 * goa study chat
 * goa study chat api
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as querystring from "querystring";
import * as url from "url";

import * as isomorphicFetch from "isomorphic-fetch";
import * as assign from "core-js/library/fn/object/assign";

interface Dictionary<T> { [index: string]: T; }
export interface FetchAPI { (url: string, init?: any): Promise<any>; }

const BASE_PATH = "http://localhost:9089/api".replace(/\/+$/, "");

export interface FetchArgs {
    url: string;
    options: any;
}

export class BaseAPI {
    basePath: string;
    fetch: FetchAPI;

    constructor(fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) {
        this.basePath = basePath;
        this.fetch = fetch;
    }
};

/**
 * A account (default view)
 */
export interface Account {
    "googleUserID": string;
    "lastLogin": Date;
    "name"?: string;
    "picture": string;
}

/**
 * AccountCollection is the media type for an array of Account (default view)
 */
export interface AccountCollection extends Array<Account> {
}

/**
 * Error response media type (default view)
 */
export interface Error {
    /**
     * an application-specific error code, expressed as a string value.
     */
    "code"?: string;
    /**
     * a human-readable explanation specific to this occurrence of the problem.
     */
    "detail"?: string;
    /**
     * a unique identifier for this particular occurrence of the problem.
     */
    "id"?: string;
    /**
     * a meta object containing non-standard meta-information about the error.
     */
    "meta"?: any;
    /**
     * the HTTP status code applicable to this problem, expressed as a string value.
     */
    "status"?: string;
}

/**
 * A Message (default view)
 */
export interface Message {
    "auther": string;
    "content": string;
    "created": Date;
    "id": number;
}

/**
 * MessageCollection is the media type for an array of Message (default view)
 */
export interface MessageCollection extends Array<Message> {
}

export interface MessagePayload {
    "auther": string;
    "content": string;
    "created": Date;
}

/**
 * A room (default view)
 */
export interface Room {
    /**
     * Date of creation
     */
    "created": Date;
    /**
     * description of room
     */
    "description": string;
    /**
     * Name of room
     */
    "name": string;
}

/**
 * RoomCollection is the media type for an array of Room (default view)
 */
export interface RoomCollection extends Array<Room> {
}

export interface RoomPayload {
    /**
     * Date of creation
     */
    "created"?: Date;
    /**
     * description of room
     */
    "description": string;
    /**
     * Name of room
     */
    "name": string;
}



/**
 * AccountApi - fetch parameter creator
 */
export const AccountApiFetchParamCreator = {
    /**
     * Retrieve account with given id or something
     * @summary show account
     * @param ids 
     */
    accountShow(params: {  "ids"?: Array<string>; }, options?: any): FetchArgs {
        const baseUrl = `/accounts`;
        let urlObj = url.parse(baseUrl, true);
        urlObj.query = assign({}, urlObj.query, {
            "ids": params["ids"],
        });
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /**
     * Retrieve my account  Required security scopes:   * `api:access`
     * @summary showMe account
     */
    accountShowMe(options?: any): FetchArgs {
        const baseUrl = `/accounts/me`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * AccountApi - functional programming interface
 */
export const AccountApiFp = {
    /**
     * Retrieve account with given id or something
     * @summary show account
     * @param ids 
     */
    accountShow(params: { "ids"?: Array<string>;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AccountCollection> {
        const fetchArgs = AccountApiFetchParamCreator.accountShow(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
    /**
     * Retrieve my account  Required security scopes:   * `api:access`
     * @summary showMe account
     */
    accountShowMe(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Account> {
        const fetchArgs = AccountApiFetchParamCreator.accountShowMe(options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * AccountApi - object-oriented interface
 */
export class AccountApi extends BaseAPI {
    /**
     * Retrieve account with given id or something
     * @summary show account
     * @param ids 
     */
    accountShow(params: {  "ids"?: Array<string>; }, options?: any) {
        return AccountApiFp.accountShow(params, options)(this.fetch, this.basePath);
    }
    /**
     * Retrieve my account  Required security scopes:   * `api:access`
     * @summary showMe account
     */
    accountShowMe(options?: any) {
        return AccountApiFp.accountShowMe(options)(this.fetch, this.basePath);
    }
};

/**
 * AccountApi - factory interface
 */
export const AccountApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieve account with given id or something
         * @summary show account
         * @param ids 
         */
        accountShow(params: {  "ids"?: Array<string>; }, options?: any) {
            return AccountApiFp.accountShow(params, options)(fetch, basePath);
        },
        /**
         * Retrieve my account  Required security scopes:   * `api:access`
         * @summary showMe account
         */
        accountShowMe(options?: any) {
            return AccountApiFp.accountShowMe(options)(fetch, basePath);
        },
    };
};


/**
 * MessageApi - fetch parameter creator
 */
export const MessageApiFetchParamCreator = {
    /**
     * Retrieve all messages.
     * @summary list message
     * @param name Name of room
     * @param limit 
     * @param offset 
     */
    messageList(params: {  "name": string; "limit"?: number; "offset"?: number; }, options?: any): FetchArgs {
        // verify required parameter "name" is set
        if (params["name"] == null) {
            throw new Error("Missing required parameter name when calling messageList");
        }
        const baseUrl = `/rooms/{name}/messages`
            .replace(`{${"name"}}`, `${ params["name"] }`);
        let urlObj = url.parse(baseUrl, true);
        urlObj.query = assign({}, urlObj.query, {
            "limit": params["limit"],
            "offset": params["offset"],
        });
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /**
     * Create new message  Required security scopes:   * `api:access`
     * @summary post message
     * @param name Name of room
     * @param payload 
     */
    messagePost(params: {  "name": string; "payload": MessagePayload; }, options?: any): FetchArgs {
        // verify required parameter "name" is set
        if (params["name"] == null) {
            throw new Error("Missing required parameter name when calling messagePost");
        }
        // verify required parameter "payload" is set
        if (params["payload"] == null) {
            throw new Error("Missing required parameter payload when calling messagePost");
        }
        const baseUrl = `/rooms/{name}/messages`
            .replace(`{${"name"}}`, `${ params["name"] }`);
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = assign({}, { method: "POST" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        contentTypeHeader = { "Content-Type": "application/json" };
        if (params["payload"]) {
            fetchOptions.body = JSON.stringify(params["payload"] || {});
        }
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /**
     * Retrieve message with given id
     * @summary show message
     * @param messageID 
     * @param name Name of room
     */
    messageShow(params: {  "messageID": number; "name": string; }, options?: any): FetchArgs {
        // verify required parameter "messageID" is set
        if (params["messageID"] == null) {
            throw new Error("Missing required parameter messageID when calling messageShow");
        }
        // verify required parameter "name" is set
        if (params["name"] == null) {
            throw new Error("Missing required parameter name when calling messageShow");
        }
        const baseUrl = `/rooms/{name}/messages/{messageID}`
            .replace(`{${"messageID"}}`, `${ params["messageID"] }`)
            .replace(`{${"name"}}`, `${ params["name"] }`);
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * MessageApi - functional programming interface
 */
export const MessageApiFp = {
    /**
     * Retrieve all messages.
     * @summary list message
     * @param name Name of room
     * @param limit 
     * @param offset 
     */
    messageList(params: { "name": string; "limit"?: number; "offset"?: number;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageCollection> {
        const fetchArgs = MessageApiFetchParamCreator.messageList(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
    /**
     * Create new message  Required security scopes:   * `api:access`
     * @summary post message
     * @param name Name of room
     * @param payload 
     */
    messagePost(params: { "name": string; "payload": MessagePayload;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
        const fetchArgs = MessageApiFetchParamCreator.messagePost(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response;
                } else {
                    throw response;
                }
            });
        };
    },
    /**
     * Retrieve message with given id
     * @summary show message
     * @param messageID 
     * @param name Name of room
     */
    messageShow(params: { "messageID": number; "name": string;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Message> {
        const fetchArgs = MessageApiFetchParamCreator.messageShow(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * MessageApi - object-oriented interface
 */
export class MessageApi extends BaseAPI {
    /**
     * Retrieve all messages.
     * @summary list message
     * @param name Name of room
     * @param limit 
     * @param offset 
     */
    messageList(params: {  "name": string; "limit"?: number; "offset"?: number; }, options?: any) {
        return MessageApiFp.messageList(params, options)(this.fetch, this.basePath);
    }
    /**
     * Create new message  Required security scopes:   * `api:access`
     * @summary post message
     * @param name Name of room
     * @param payload 
     */
    messagePost(params: {  "name": string; "payload": MessagePayload; }, options?: any) {
        return MessageApiFp.messagePost(params, options)(this.fetch, this.basePath);
    }
    /**
     * Retrieve message with given id
     * @summary show message
     * @param messageID 
     * @param name Name of room
     */
    messageShow(params: {  "messageID": number; "name": string; }, options?: any) {
        return MessageApiFp.messageShow(params, options)(this.fetch, this.basePath);
    }
};

/**
 * MessageApi - factory interface
 */
export const MessageApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieve all messages.
         * @summary list message
         * @param name Name of room
         * @param limit 
         * @param offset 
         */
        messageList(params: {  "name": string; "limit"?: number; "offset"?: number; }, options?: any) {
            return MessageApiFp.messageList(params, options)(fetch, basePath);
        },
        /**
         * Create new message  Required security scopes:   * `api:access`
         * @summary post message
         * @param name Name of room
         * @param payload 
         */
        messagePost(params: {  "name": string; "payload": MessagePayload; }, options?: any) {
            return MessageApiFp.messagePost(params, options)(fetch, basePath);
        },
        /**
         * Retrieve message with given id
         * @summary show message
         * @param messageID 
         * @param name Name of room
         */
        messageShow(params: {  "messageID": number; "name": string; }, options?: any) {
            return MessageApiFp.messageShow(params, options)(fetch, basePath);
        },
    };
};


/**
 * RoomApi - fetch parameter creator
 */
export const RoomApiFetchParamCreator = {
    /**
     * Retrieve all rooms.
     * @summary list room
     * @param limit 
     * @param offset 
     */
    roomList(params: {  "limit"?: number; "offset"?: number; }, options?: any): FetchArgs {
        const baseUrl = `/rooms`;
        let urlObj = url.parse(baseUrl, true);
        urlObj.query = assign({}, urlObj.query, {
            "limit": params["limit"],
            "offset": params["offset"],
        });
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /**
     * Create new Room  Required security scopes:   * `api:access`
     * @summary post room
     * @param payload 
     */
    roomPost(params: {  "payload": RoomPayload; }, options?: any): FetchArgs {
        // verify required parameter "payload" is set
        if (params["payload"] == null) {
            throw new Error("Missing required parameter payload when calling roomPost");
        }
        const baseUrl = `/rooms`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = assign({}, { method: "POST" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        contentTypeHeader = { "Content-Type": "application/json" };
        if (params["payload"]) {
            fetchOptions.body = JSON.stringify(params["payload"] || {});
        }
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /**
     * Retrieve room with given name
     * @summary show room
     * @param name Name of room
     */
    roomShow(params: {  "name": string; }, options?: any): FetchArgs {
        // verify required parameter "name" is set
        if (params["name"] == null) {
            throw new Error("Missing required parameter name when calling roomShow");
        }
        const baseUrl = `/rooms/{name}`
            .replace(`{${"name"}}`, `${ params["name"] }`);
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = {};
        if (contentTypeHeader) {
            fetchOptions.headers = assign({}, contentTypeHeader, fetchOptions.headers);
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * RoomApi - functional programming interface
 */
export const RoomApiFp = {
    /**
     * Retrieve all rooms.
     * @summary list room
     * @param limit 
     * @param offset 
     */
    roomList(params: { "limit"?: number; "offset"?: number;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<RoomCollection> {
        const fetchArgs = RoomApiFetchParamCreator.roomList(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
    /**
     * Create new Room  Required security scopes:   * `api:access`
     * @summary post room
     * @param payload 
     */
    roomPost(params: { "payload": RoomPayload;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
        const fetchArgs = RoomApiFetchParamCreator.roomPost(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response;
                } else {
                    throw response;
                }
            });
        };
    },
    /**
     * Retrieve room with given name
     * @summary show room
     * @param name Name of room
     */
    roomShow(params: { "name": string;  }, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Room> {
        const fetchArgs = RoomApiFetchParamCreator.roomShow(params, options);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * RoomApi - object-oriented interface
 */
export class RoomApi extends BaseAPI {
    /**
     * Retrieve all rooms.
     * @summary list room
     * @param limit 
     * @param offset 
     */
    roomList(params: {  "limit"?: number; "offset"?: number; }, options?: any) {
        return RoomApiFp.roomList(params, options)(this.fetch, this.basePath);
    }
    /**
     * Create new Room  Required security scopes:   * `api:access`
     * @summary post room
     * @param payload 
     */
    roomPost(params: {  "payload": RoomPayload; }, options?: any) {
        return RoomApiFp.roomPost(params, options)(this.fetch, this.basePath);
    }
    /**
     * Retrieve room with given name
     * @summary show room
     * @param name Name of room
     */
    roomShow(params: {  "name": string; }, options?: any) {
        return RoomApiFp.roomShow(params, options)(this.fetch, this.basePath);
    }
};

/**
 * RoomApi - factory interface
 */
export const RoomApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieve all rooms.
         * @summary list room
         * @param limit 
         * @param offset 
         */
        roomList(params: {  "limit"?: number; "offset"?: number; }, options?: any) {
            return RoomApiFp.roomList(params, options)(fetch, basePath);
        },
        /**
         * Create new Room  Required security scopes:   * `api:access`
         * @summary post room
         * @param payload 
         */
        roomPost(params: {  "payload": RoomPayload; }, options?: any) {
            return RoomApiFp.roomPost(params, options)(fetch, basePath);
        },
        /**
         * Retrieve room with given name
         * @summary show room
         * @param name Name of room
         */
        roomShow(params: {  "name": string; }, options?: any) {
            return RoomApiFp.roomShow(params, options)(fetch, basePath);
        },
    };
};

